### ISSUE TITLE
Use rolling averages

### ISSUE THREAD

**Issue by oskarth** [status-im/analytics.status.im#3]
A lot of spiky graphs, use of rolling averages (3d, 7d) would make trend more clear.

**Comment by tersec** [comment]
These are easy enough if people want them -- Prometheus's queries control time interval frequency of query and their rolling-average time intervals orthogonally. I initially did have some daily-but-averaged-over-last-7 day charts, for which I found no interest.

**Comment by jakubgs** [comment]
Outdated.
